version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:ff2c2a3fd5105396697de4c20139435fe9f47d62716fa241d225122deb711d50
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
